stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - web
  script:
    - whoami
    - export SASS_BINARY_PATH=/opt/node-saas/linux-x64-83_binding.node
    - npm i --unsafe-perm=true --allow-root --registry https://registry.npm.taobao.org
    - npm run build:test
  artifacts:
    paths:
      - dist/
  cache:
    paths:
      - node_modules/
  only:
    - test
deploy:
  stage: deploy
  tags:
    - web
  script:
    - project_path=$(cd `dirname $0`; pwd)
    - scp -r dist/* root@192.168.100.106:/usr/local/wwwroot/m
  only:
    - test
